In [2]:
import gym
from gym_minigrid.wrappers import *
import numpy as np
import torch

In [40]:
env = gym.make('MiniGrid-DistShift1-v0')

env = ImgObsWrapper(env) # Get rid o
#env = FlatObsWrapper(env) # Get flat observationo
obs = env.reset() # This now produces an RGB tensor only
print(obs.shape)
# minigrid consists of object_ids, color_ids and state ids
print(obs[:,:,0])
print(obs[:,:,1])
print(env.action_space.n)
for i in range(4):
    action = 0
    print(action)
    obs, _, _, _ = env.step(action)
    print(obs.shape)
    print(obs[:,:,0])

(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [8 1 9 9 9 1 1]
 [1 1 9 9 9 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
7
0
(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 9]
 [2 2 2 2 2 2 9]]
0
(7, 7, 3)
[[2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
0
(7, 7, 3)
[[2 2 1 1 1 9 9]
 [2 2 1 1 1 9 9]
 [2 2 1 1 1 1 1]
 [2 2 1 1 1 1 1]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
0
(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [8 1 9 9 9 1 1]
 [1 1 9 9 9 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [25]:
test = np.ones((3,1)) - 5
test[0] = 0

print(np.max(test[np.where(test)[0]]))

print(np.exp(-1/500))

-4.0
0.9980019986673331


In [20]:
test = np.asarray([[1,2,3], [1,2,3], [1,2,3]])
test2 = np.asarray([[1,2,3]])
print(test, test2, test2.shape)
print(np.concatenate((test, np.repeat(test2,3, axis=0)), axis=1))

[[1 2 3]
 [1 2 3]
 [1 2 3]] [[1 2 3]] (1, 3)
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]
