In [1]:
import gym
from gym_minigrid.wrappers import *
import numpy as np
import torch

In [2]:
env = gym.make('MiniGrid-DistShift1-v0')

env = ImgObsWrapper(env) # Get rid o
#env = FlatObsWrapper(env) # Get flat observationo
obs = env.reset() # This now produces an RGB tensor only
print(obs.shape)
# minigrid consists of object_ids, color_ids and state ids
print(obs[:,:,0])
print(obs[:,:,1])
print(env.action_space.n)
for i in range(4):
    action = 0
    print(action)
    obs, _, _, _ = env.step(action)
    print(obs.shape)
    print(obs[:,:,0])

(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [8 1 9 9 9 1 1]
 [1 1 9 9 9 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
7
0
(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 9]
 [2 2 2 2 2 2 9]]
0
(7, 7, 3)
[[2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 1]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
0
(7, 7, 3)
[[2 2 1 1 1 9 9]
 [2 2 1 1 1 9 9]
 [2 2 1 1 1 1 1]
 [2 2 1 1 1 1 1]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]
0
(7, 7, 3)
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [8 1 9 9 9 1 1]
 [1 1 9 9 9 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [25]:
test = np.ones((3,1)) - 5
test[0] = 0

print(np.max(test[np.where(test)[0]]))

print(np.exp(-1/500))

-4.0
0.9980019986673331


In [20]:
test = np.asarray([[1,2,3], [1,2,3], [1,2,3]])
test2 = np.asarray([[1,2,3]])
print(test, test2, test2.shape)
print(np.concatenate((test, np.repeat(test2,3, axis=0)), axis=1))

[[1 2 3]
 [1 2 3]
 [1 2 3]] [[1 2 3]] (1, 3)
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [4]:
a = torch.FloatTensor([np.nan])
print(a)


tensor([nan])


In [23]:
import os, pickle

with open(os.path.join("data", f"ex6", f"MiniGrid-LavaGapS6-v0_run1_fully.pkl"), "rb") as f:
    buffer = pickle.load(f)

print(buffer.state.shape)
print(buffer.reward.shape)
print(buffer.current_size - buffer.not_done.sum())
print(buffer.reward.sum() / (buffer.current_size - buffer.not_done.sum()))

(100001, 98)
(100000, 1)
2335
0.7072805139186296


In [6]:
test = torch.ones((5,5))
action = torch.ones((5,1), dtype=torch.int64)

print(torch.logsumexp(test, dim=1).shape)
print(test.gather(1, action).squeeze(1).shape)

torch.Size([5])
torch.Size([5])


In [5]:
import pickle

buffer = pickle.load(open("data/ex5/MountainCar-v0_run1_random.pkl", "rb"))

for _ in range(10):
    state, action, next_state, reward, done = buffer.sample()
    print(state)

tensor([[-8.4660e-01, -9.0464e-03],
        [-5.6825e-01, -4.8412e-03],
        [-3.5532e-01, -1.1162e-02],
        [-5.3666e-01, -7.8463e-03],
        [-6.0196e-01, -6.4120e-03],
        [-4.8460e-01,  3.8468e-04],
        [-5.2447e-01,  7.7787e-04],
        [-4.8220e-01, -4.2646e-03],
        [-5.7422e-01, -2.7340e-03],
        [-3.7585e-01, -3.5364e-03],
        [-5.4741e-01, -1.9818e-03],
        [-4.8169e-01,  1.9118e-03],
        [-6.0972e-01,  1.1156e-02],
        [-5.6234e-01, -1.3806e-03],
        [-4.5766e-01, -6.7774e-03],
        [-5.4820e-01,  1.7357e-03],
        [-5.7894e-01, -3.6848e-03],
        [-3.7096e-01,  8.3042e-04],
        [-5.6080e-01, -7.6471e-03],
        [-5.1906e-01, -2.0119e-02],
        [-6.0765e-01,  6.3354e-03],
        [-3.7843e-01,  1.2915e-02],
        [-5.2159e-01,  8.6390e-04],
        [-3.9109e-01, -1.5293e-03],
        [-2.9960e-01,  1.6599e-02],
        [-5.2071e-01,  3.1519e-03],
        [-4.8328e-01,  8.4810e-04],
        [-2.8592e-01, -1.709

In [4]:
import numpy as np
import struct


In [5]:
def binary(num):
    return ''.join('{:0>8b}'.format(c) for c in struct.pack('!f', num))

In [36]:
print(binary(1.01))
print(binary(1.0100001))
print(binary(0.0038276))

00111111100000010100011110101110
00111111100000010100011110101111
00111011011110101101100001111001


In [33]:
import hyperloglog
hll = hyperloglog.HyperLogLog(0.01)  # accept 1% counting error
hll.add(binary(1.01))
hll.add(binary(1.01000001))
hll.add(binary(0.0038276))
print(len(hll))

2
